version: "3"

services:
#   postgres:
#     build:
#       context: .
#       dockerfile: ./docker/pg-Dockerfile
#     ports:
#       - 5432:5432
#     volumes:
#       - .data/postgres:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: postgres
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

  subquery-node:
    image: onfinality/subql-node:v1.18.0
    # depends_on:
    #   - "postgres"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: rainbow6-test-polkadot-db-123
      DB_DATABASE: postgres
      DB_HOST: 172.19.0.35
      DB_PORT: 30445
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --db-schema=polkadot
      - --disable-historical=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node:3000/ready"]
      interval: 3s
      timeout: 5s
      retries: 10
