specVersion: 0.2.0
name: subql_behavioral_incentives
version: 1.0.0
description: For Bifrost behavioral incentives project
repository: https://github.com/subquery/bifrost-subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://bifrost-parachain.api.onfinality.io/public-ws
  genesisHash: '0x9f28c6a68e0fc9646eff64935684f6eeeece527e37bbe1f213d22caa1d9d6bed'
  dictionary: https://api.subquery.network/sq/subquery/bifrost-parachain-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1500000
    mapping:
      file: ./dist/index.js
      handlers:
        # Update current block
        - handler: handleBlock
          kind: substrate/BlockHandler
        # ParachainStaking module handlers
        - handler: handleParachainStakingDelegation
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: Delegation
        - handler: handleParachainStakingDelegationIncreased
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: DelegationIncreased
        - handler: handleParachainStakingDelegationDecreased
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: DelegationDecreased
        - handler: handleParachainStakingDelegationRevoked
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: DelegationRevoked
      #VtokenMinting module handlers
        - handler: handleVtokenMintingMinted
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: Minted
        - handler: handleVtokenMintingRedeemed
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: Redeemed
      #Currencies module handlers
        - handler: handleVtokenTransferOut
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred

