specVersion: 1.0.0
name: subql_behavioral_incentives
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: For Bifrost behavioral incentives project
repository: https://github.com/subquery/bifrost-subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://hk.p.bifrost-rpc.liebi.com/ws
  chainId: '0x262e1b2ad728475fd6fe88e62d34c200abe6fd693931ddad144059b1eb884e5b'
  dictionary: 
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1634220
    mapping:
      file: ./dist/index.js
      handlers:
      # Update current block
        - handler: handleBlock
          kind: substrate/BlockHandler
      #VtokenMinting module handlers
        - handler: handleVtokenMintingMinted
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: Minted
        - handler: handleVtokenMintingRedeemed
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: Redeemed
      #Currencies module handlers
        - handler: handleVtokenTransferOut
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Transfer
